// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hlzn1.Blog.Data;

#nullable disable

namespace hlzn1.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20250507191952_FirstBlog")]
    partial class FirstBlog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "BlogPostSectionContentType", new[] { "audio", "code", "image", "link", "list", "other", "quote", "table", "text", "video" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hlzn1.DataModels.Blog.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key of the entity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("When the entity was created");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasComment("Is the blog post public?");

                    b.Property<string>("Preview")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text")
                        .HasComment("Preview of the blog post");

                    b.Property<string>("PreviewImageSource")
                        .HasColumnType("text")
                        .HasComment("The preview size image of the blog post");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When the blog post was published");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasComment("The tags of the blog post");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("The title of the blog post");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("When the entity was last updated");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts", "public", t =>
                        {
                            t.HasComment("Table storing blog posts");
                        });
                });

            modelBuilder.Entity("hlzn1.DataModels.Blog.BlogPostSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Primary key of the entity");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogPostId")
                        .HasColumnType("integer")
                        .HasComment("The ID of the associated blog post");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("The content of the blog post section");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ContentType")
                        .HasComment("The type of content in the blog post section");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("When the entity was created");

                    b.Property<int>("Index")
                        .HasColumnType("integer")
                        .HasComment("The order of the section in the blog post");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()")
                        .HasComment("When the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("BlogPostId");

                    b.ToTable("BlogPostSections", "public", t =>
                        {
                            t.HasComment("Table storing sections of blog posts");
                        });
                });

            modelBuilder.Entity("hlzn1.DataModels.Blog.BlogPostSection", b =>
                {
                    b.HasOne("hlzn1.DataModels.Blog.BlogPost", "BlogPost")
                        .WithMany()
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlogPost");
                });
#pragma warning restore 612, 618
        }
    }
}
